package effects;

public enum EffectType {

	EVENT_CANCELLED, CARD_PLAYED, TURN_START, TURN_END, CARD_DAMAGED, PLAYER_DAMAGED, CARD_DRAWN, CREATURE_DIED, PLAYER_ATTACKED, CREATURE_ATTACKED, CARD_CREATED, HEALTH_CHANGE, ATTACK_CHANGE, PLAYER_HEALED, CARD_HEALED, CARD_TARGETED, CARD_ZONE_CHANGED, ELEMENT_GAINED, CARD_CHOSEN, PLAYER_TARGETED, EMPTY, GATE_EFFECT, MAKER, EFFECT_CANCELLED, CARD_APPLIED_TO, TRANSFORM, CARD_SUMMONED, CONCAT, AOE_DAMAGE, SET_DEVOTION,

}
